site_name: AnchorPy
theme:
  name: material
  palette:
    - scheme: default
      primary: lime
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: overrides
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.snippets
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
repo_url: https://github.com/kevinheavey/anchorpy
repo_name: kevinheavey/anchorpy
nav:
  - index.md
  - tutorial.md
  - testing.md