[tool.poetry]
name = "anchorpy"
version = "0.1.0"
description = ""
authors = ["kevinheavey <kevinheavey123@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
construct-typing = "^0.5.1"
solana = "^0.11.1"
httpx = "^0.18.2"
typedload = "^2.8"
pydantic = "^1.8.2"
inflection = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
wemake-python-styleguide = "^0.15.3"
pytest-docker = "^0.10.3"
mypy = "^0.910"
black = "^21.7b0"
pytest-asyncio = "^0.15.1"
pydocstyle = "^6.1.1"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
