name: Nox
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  solana_verion: 1.8.0
jobs:
  nox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Solana
      if: steps.cache-solana.outputs.cache-hit != 'true'
      run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.solana_verion }}/install)"

    - name: Add Solana to path
      run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Generate local keypair
      run: yes | solana-keygen new

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.10
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install nox-poetry
      run: pip install nox-poetry
    - run: nox
