name: Python version
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: See Python version
      run: python -V

    - name: Try error
      run: python -c "list[int]"

    - name: Run bad file
      run: python python_version.py
