name: Tests
on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install Solana
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.7.11/install)"

      - name: Add Solana to path
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor CLI
        run: npm i -g @project-serum/anchor-cli

      - name: Generate local keypair
        run: yes | solana-keygen new

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.7

      - name: Install Python dev deps
        run: poetry install

  tests:
      runs-on: ubuntu-latest
      needs: setup
      steps:
        - name: Run tests
          run: poetry run pytest tests/test_basic_0.py
