name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  solana_verion: 1.10.8
  anchor_version: 0.24.2

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [
            "test_basic_0",
            "test_basic_1",
            "test_basic_2",
            "test_basic_3",
            "test_cashiers_check",
            "test_chat",
            "test_cli",
            "test_cli_init",
            "test_composite",
            "test_errors",
            # "test_escrow",
            "test_events",
            "test_misc",
            "test_multisig",
            "test_pyth",
            # "test_swap",
            "test_sysvars",
            "test_system_accounts",
            # "test_token_proxy",
            "test_zero_copy",
            "client_gen/test_client_gen",
          ]
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Cache Solana Tool Suite
        uses: actions/cache@v2
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0000-${{ env.solana_verion }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install Solana
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.solana_verion }}/install)"

      - name: Add Solana to path
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: install Anchor CLI
        run: npm install -g @project-serum/anchor-cli@${{ env.anchor_version }}

      - name: Generate local keypair
        run: solana-keygen new --no-bip39-passphrase

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.10
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install -E cli --no-interaction --no-root
      #----------------------------------------------
      # install your root project
      #----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: poetry run pytest tests/${{ matrix.node }}.py

  all_good:
    # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: note that all tests succeeded
        run: echo "🎉"
